Repository rancilio-pid/clevercoffee, pull requests merged in 2025-06, with the labels that each got.

#553 add info about chossing branch
  CONTRIBUTING.md
Labels: enhancement

#552 remove brew(), manualFlush() call outside main state machine
  src/main.cpp
Labels: bug

#554 Update espressif framework and several libraries
  platformio.ini
  src/Config.h
  src/embeddedWebserver.h
  src/mqtt.h
Labels: enhancement

#557 Code cleanup, fix clang-tidy warnings, fix formatting
  src/Config.h
  src/ParameterRegistry.h
  src/brewHandler.h
  src/display/displayCommon.h
  src/display/displayTemplateManager.h
  src/display/displayTemplateScale.h
  src/display/displayTemplateStandard.h
  src/display/displayTemplateTempOnly.h
  src/display/displayTemplateUpright.h
  src/display/languages.h
  src/embeddedWebserver.h
  src/hardware/GPIOPin.cpp
  src/hardware/GPIOPin.h
  src/hardware/IOSwitch.cpp
  src/hardware/IOSwitch.h
  src/hardware/LED.h
  src/hardware/Relay.cpp
  src/hardware/Relay.h
  src/hardware/StandardLED.cpp
  src/hardware/StandardLED.h
  src/hardware/Switch.h
  src/hardware/TempSensor.h
  src/hardware/TempSensorDallas.cpp
  src/hardware/TempSensorDallas.h
  src/hardware/TempSensorTSIC.cpp
  src/hardware/TempSensorTSIC.h
  src/hardware/pressureSensor.h
  src/scaleHandler.h
  src/standby.h
  src/steamHandler.h
  src/utils/Timer.cpp
  src/utils/Timer.h
Labels: cleanup

#558 Order parameters withing sections
  src/ParameterRegistry.cpp
Labels: enhancement

#564 Handle detached HEAD during build gracefully
  auto_firmware_version.py
Labels: bug
